attributes:
  auth_provider:
    type: "radio"
    weight: 10
    value: "htaccess"
    label: "Authentication Provider"
    values:
      - data: "htaccess"
        label: "htaccess"
      - data: "ldap"
        label: "ldap"

  nagios_user:
    value: 'nagiosadmin'
    label: 'Nagios user'
    description: 'The Username to access the Nagios Web Interface (default: "nagiosadmin")'
    weight: 15
    type: "text"
    regex:
      source: '\S'
      error: "Invalid value"

  nagios_password:
    value: 'r00tme'
    label: 'Nagios password'
    description: 'The password to access the Nagios Web Interface'
    weight: 16
    type: "password"
    regex:
      source: '\S'
      error: "Invalid value"
  ldap_url:
    value: 'ldaps://yourldapserverIPorFQDN'
    label: 'LDAP server URL'
    description: 'LDAP Server URL (prefix ldap:// or ldaps:// for protocol)'
    weight: 21
    type: "text"
    regex:
      source: '^(ldap://|ldaps://){1}[a-zA-Z\d][a-zA-Z\d_\-.]+(:[0-9]+)?$'
      error: 'Invalid ldap url or name'
    restrictions:
      - condition: "settings:lma_infrastructure_alerting.auth_provider.value != 'ldap'"
        action: hide

  ldap_bind_dn:
    value: ''
    label: 'Nagios ldap bind DN'
    description: 'LDAP DN to bind with'
    weight: 23
    type: "text"
    regex:
      source: '\S'
      error: "Invalid value"
    restrictions:
      - condition: "settings:lma_infrastructure_alerting.auth_provider.value != 'ldap'"
        action: hide

  notify_critical:
    type: "checkbox"
    weight: 43
    value: true
    label: "Receive CRITICAL notifications by email"

  notify_warning:
    type: "checkbox"
    weight: 44
    value: true
    label: "Receive WARNING notifications by email"

  notify_unknown:
    type: "checkbox"
    weight: 45
    value: true
    label: "Receive UNKNOWN notifications by email"

  notify_recovery:
    type: "checkbox"
    weight: 46
    value: true
    label: "Receive RECOVERY notifications by email"

  send_to:
    value: ''
    label: 'The recipient email address'
    description: 'The recipient for the alert notifications'
    weight: 47
    type: "text"
    regex: &email
      source: '[a-z0-9!#$%&*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&*+/=?^_`{|}~-]+)*@(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.?)?[a-z0-9]?(?:[a-z0-9-]*[a-z0-9])?'
      error: "Invalid Email"
    restrictions: &disable_notifications
        - condition: "settings:lma_infrastructure_alerting.notify_critical.value == false and settings:lma_infrastructure_alerting.notify_warning.value == false and settings:lma_infrastructure_alerting.notify_unknown.value == false and settings:lma_infrastructure_alerting.notify_recovery.value == false"
          action: "disable"

  send_from:
    value: ''
    label: 'The sender email address'
    description: ''
    weight: 48
    type: "text"
    regex: *email
    restrictions: *disable_notifications

  smtp_host:
    value: ''
    label: 'SMTP server IP and port'
    description: 'ie: 10.2.2.3:25'
    weight: 49
    type: "text"
    regex:
      source: '^[a-zA-Z\d][a-zA-Z\d_\-.]+(:[0-9]+)?$'
      error: 'Invalid address or name'
    restrictions: *disable_notifications

  smtp_auth:
    type: "radio"
    weight: 50
    value: "none"
    label: "SMTP authentication method"
    values:
      - data: "none"
        label: "None"
      - data: "login"
        label: "Login"
      - data: "plain"
        label: "Plain"
      - data: "cram-md5"
        label: "CRAMMD5"
    restrictions: *disable_notifications

  smtp_user:
    value: ''
    label: 'SMTP user'
    description: ''
    weight: 51
    type: "text"
    restrictions: &no_auth
        - condition: "settings:lma_infrastructure_alerting.smtp_auth.value == 'none'"
          action: "disable"
        - condition: "settings:lma_infrastructure_alerting.notify_critical.value == false and settings:lma_infrastructure_alerting.notify_warning.value == false and settings:lma_infrastructure_alerting.notify_unknown.value == false and settings:lma_infrastructure_alerting.notify_recovery.value == false"
          action: "disable"

  smtp_password:
    value: ''
    label: 'SMTP password'
    description: ''
    weight: 52
    type: "password"
    restrictions: *no_auth
